name = "SCFQFT"
uuid = "89a0a5ea-a54d-5819-a7ed-290244e78af6"
authors = ["hz-xiaxz <1806656034@qq.com> and contributors"]
version = "0.1.0"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
GreenFunc = "9efc7ea6-d529-4241-ab29-dcf68b94af7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
FFTW = "1.8.0"
GreenFunc = "0.2.5"
LinearAlgebra = "1.11.0"
SpecialFunctions = "2.5.0"
julia = "1.10"
