name = "SCFQFT"
uuid = "89a0a5ea-a54d-5819-a7ed-290244e78af6"
authors = ["hz-xiaxz <1806656034@qq.com> and contributors"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
LinearAlgebra = "1.11.0"
julia = "1.10"
