name = "SCFQFT"
uuid = "89a0a5ea-a54d-5819-a7ed-290244e78af6"
authors = ["hz-xiaxz <1806656034@qq.com> and contributors"]
version = "0.1.0"

[deps]
CompositeGrids = "b5136c89-beeb-4521-9139-60d2cac8be56"
GreenFunc = "9efc7ea6-d529-4241-ab29-dcf68b94af7c"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"

[compat]
CompositeGrids = "0.1.3"
GreenFunc = "0.2.5"
SpecialFunctions = "2.5.0"
julia = "1.10"
